### ISSUE TITLE
nodejs 下 import 出错

### ISSUE THREAD

**Issue by wilddylan** [monkeycz/python.js#5]
var python = require('python.js');
var sys = python.import('sys');
var os = python.import('os');

var tests = python.import('tests');

最后`var tests = python.import('tests');`的时候出错了，

```
var tests = python.import('tests');
                         ^
Error: No module named tests
```

这是什么情况？ 该如何引入呢。

**Comment by smarttang** [comment]
估计是找不到路径，你可以先设置下sys的搜索路径先，然后再去import
